version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "yapf"

[[transformers]]
name = "isort"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"